// Разница будет видна внутри функции и при добавлении return или throw

// function func() {
//     try {
//         начать работу
//         работать
//         return
//     } catch (e) {
//         обработать ошибку
//         return
//     } finally {
//         очистить рабочее пространство
//     }
// }

// В первом случае код внутри finally выполнится в любом случае

// function func() {
//     try {
//         начать работу
//         работать
//         return
//     } catch (e) {
//         обработать ошибку
//         return
//     }
//
//     очистить рабочее пространство
// }

// Здесь код очистки не выполнится потому что try или catch уже вернёт
// какие-то данные